### PR TITLE
Add a bash script to split the existing Readme.md into chapters+summary files which mdBook can consume

### PR DESCRIPTION
**Pull request by nisrulz**
- Enables generating a book version
- Fixes issue #11

### CODE REVIEW

**Comment by Dhghomon** [comment]
Thanks for making this! I'm not very familiar with Bash so tell me if I'm reading this right: this creates two new files, one of which has the Bash script that the user then uses on the command line to generate the mdBook?

Or does it automatically do that inside the existing easy_rust directory as soon as I merge the request?

**Comment by nisrulz** [comment]
This will not do anything as soon as you merge the PR.

I wasn't sure you would want anything to start automatically. What this enables is that whoever is interested in the mdBook version, can run the bash script inside a terminal and it will:
1. Read your README.md file
1. Split the README.md file into chapters (each being a markdown file), by detecting when the `## ` is encountered inside your README.md file.
1. Create a folder named `src` and move all the chapter file into it.
1. Read all the chapter files and extract the title of that to create a SUMMARY.md file (mdBook needs that).
1. Once all of this is done, it will on the local system, build these files as a mdBook and start serving locally to an address i.e `http://127.0.0.1:3000`. So if you open `http://127.0.0.1:3000` in your browser you will the mdBook version of your file as a searcheable and indexed webpage in a format of a book.

NOTE:
It doesnot modify your README.md file. You continue writing the way you do. This script only reads your file.
It only depends on the header your create in your README.md file.

**Comment by Dhghomon** [comment]
Perfect! Thank you - I will merge it now.

**Comment by oren** [comment]
just FYI: on Ubuntu I had to change gcsplit to csplit and mdBook to mbdook.

**Pull request merged**
