### PR TITLE
s/reach/get

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Comment by Dhghomon** [comment]
I think I'll leave this one as is - get usually means trying to pull a value out of a vec or something whereas with `*` to get behind the `&` we're just trying to reach it to do other things (compare it, read it, etc.)

**Comment by pickfire** [comment]
I don't understand how does reach mean compare and read, it takes a while for me to guess the meaning.

**Comment by Dhghomon** [comment]
Reach doesn't mean compare and read, no. But to compare, read etc. a value you need to reach it.

I did think about "get to" (like arrive) but split verbs (run up, run down, get to, get down, etc.) are even harder for non-native speakers.

This is a good example of how the book is in simple English but not a book to learn English. It is written under the assumption that the reader will know what I mean when I write words like "reach".

On the other hand, it also makes it easy to translate! If someone doesn't know the meaning of the word "reach" then maybe it would be a good idea to translate the whole book for them (once it's done - I'm still writing it).

**Comment by pickfire** [comment]
I can read English, but "reach" is a bit hard for me to understand in that context, not sure if using "reach" is understandable by others as well. Maybe we could find another term easier to understand compared to "reach" but does not conflict with the meaning of "get"?

**Comment by Lythenas** [comment]
IMO using reach is pretty good here. Without `*` you would (if that was possible) add 10 to the reference (which is basically like a pointer/address). But we want to add 10 the memory location where the reference points to so we have to take an indirection (the `*`) to read the memory location behind the reference.

Maybe it would make it clearer to write "To reach the memory location where the value is" or something like that.

**Comment by Dhghomon** [comment]
Yeah, reach tends to be use in the same manner in a lot of languages: reichen and the other forms in other Germanic languages plus atteindre and the other forms in Romance languages at least.

Maybe I'll go with "to reach the place where the value is" to keep reach but make it a bit clearer.

**Comment by pickfire** [comment]
Yes, that's clearer. I guess I will close this issue.

**Pull request closed without merging**
